### ISSUE TITLE
Support walls WPJ files

### ISSUE THREAD

**Issue by jlillest** [jedwards1211/dewalls#4]
The WPJ files is the file that pulls in the rest of the Walls Survey files (*.srv).  Dewalls should support this.

**Comment by jedwards1211** [comment]
Do you know if there's a full specification for WPJ files somewhere?  I haven't seen one, but I don't know.  They can be kind of weird, for instance there are some magic numbers that indicate whether you selected feed or meters in the review settings in Walls.

And I'm always a bit wary of reverse engineering, because you can say you support something and then it turns out there's some obscure feature of the format you've never seen :)  Compass has this unfortunately...the online documentation has no mention of using -999.00 to mean no measurement taken, and there are some undocumented flags as well.

**Comment by jedwards1211** [comment]
I've started working on this! :)

I have a hacky version working in some branch, but I reverse-engineered as many of the `.STATUS` bits as I could and also the `.REF` format, and I've started writing the parser for those in the [wpj-import](https://github.com/jedwards1211/dewalls/tree/wpj-parser) branch.

**Comment by jedwards1211** [comment]
@jlillest you were right, importing from the .wpj is the only thing that makes sense.  It contains extra #units options passed to the survey files (meaning importing the .srv files without those options may be incorrect), as well as geodetic references for the data.  I'm thinking I shouldn't even support importing raw .srv files anymore.

**Comment by jlillest** [comment]
Awesome, it was a busy Thanksgiving so I'm playing catchup.  I had fully intended to help you start working on this at some point, but It seems that I'm behind on everything.

From a usability standpoint, I'd leave support for importing single .srv files.  There are users that may need to import their old data and may not have created a wpj file.

**Comment by jedwards1211** [comment]
No worries, I just happened to have plenty of time on my hands this weekend :)

Fair enough, I guess I'll just make the .wpj file filter selected by default, and then users can pick the .srv filter instead if they want.  That way they wouldn't be likely to accidentally import directly from the .srv files if they have a valid .wpj.

**Comment by jedwards1211** [comment]
wpj import is done in this project, I'll open an issue about putting back in direct import of .srv files in the Cavewhere page.
